config/routes.rb
Rails.application.routes.draw do
root :to => "articles#index"
resources :articles do
member do
post :notify_friend
end
resources :comments
end
resources :users
resource :session
get '/login' => "sessions#new", :as => "login"
get '/logout' => "sessions#destroy", :as => "logout"

resources :users do
    member do
      get :confirm_email
    end
  end

end

app/views/notifier/comment_added.html.erb
<html>
<body>
<p>
Someone added a comment to one of your articles <i><%= @article.title %></i>.
Go read the comment: <%= link_to @article.title,
article_url(@article, host:'https://rails-madhu-blog.herokuapp.com') %>.
</p>
</body>
</html>





<!-- :host => 'localhost:3000' -->

app/views/notifier/email_friend.html.erb
<html>
<body>
<p>
One of your friends, <%= @sender_name %>,
thinks you like an article we have written.
</p>
 
<p>
Come check all the information about <strong><%= @article.title %></strong> at
<%= article_url @article, :host => 'https://rails-madhu-blog.herokuapp.com' %>
</p>
</body>
</html>

app/views/notifier/email_friend.text.erb
Your friend madhu j<%= @sender_name %> must read this article:
 
<%= @article.title %>: <%= article_url(@article, :host => "localhost:3000") %>

<!-- host:'https://rails-madhu-blog.herokuapp.com'
 -->

<!-- :host => "localhost:3000" -->

app/views/notifier/registration_confirmation.html.erb
Hi <%= @message %>,
<%= @user.email %>,

Thanks for registering! To confirm your registration click the URL below.

<%= confirm_email_user_url(@user.confirm_token) %>