config/routes.rb
Rails.application.routes.draw do
root :to => "articles#index"
resources :articles do
member do
post :notify_friend
end
resources :comments
end
resources :users
resource :session
get '/login' => "sessions#new", :as => "login"
get '/logout' => "sessions#destroy", :as => "logout"

resources :users do
    member do
      get :confirm_email
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Blog</title>
<%= stylesheet_link_tag 'application',  params[:controller], media: 'all', 'data-turbolinks-track' => true %>  
<%= javascript_include_tag  'application',  params[:controller] ,  'data-turbolinks-track' => true%>
    
<!-- Latest compiled and minified CSS -->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"> -->

<!-- Optional theme -->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css"> -->

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<!-- <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script> -->
<%= csrf_meta_tag %>
</head>
<body>
<div id="header">
<h1><%= link_to "Madhu Rails Blog ", root_path %></h1>
<div id="user_bar">
<% if logged_in? %>
<%= link_to "New Article", new_article_path %> |
<%= link_to "Edit Password", edit_user_path(current_user) %> |
<%= link_to "Logout", logout_path %>
<% else %>
<%= link_to "Login", login_path %>
<%= link_to "signup",  new_user_path %>
<% end %>
</div>
</div>
<div id="main">
<%= content_tag(:p, notice, class: 'notice') if notice.present? %>
<%= content_tag(:p, alert, class: 'alert') if alert.present? %>
<%= yield %>
</div>
<div id="footer">
A simple blog built for the book
<a href="http://guides.rubyonrails.org/">Beginning Rails 4</a>
</div>
</body>
</html>